#!/usr/bin/perl -w
use strict;
use JSON::XS;
$|=1;
sub dumpmap($);

my %pkgmapsrcbin=();
my %pkgmapsrcdep=();

for my $filename (<buildinfo/*>) {
  my $pkg = $filename; $pkg=~s!.*/!!;
  my $xml=qx(cat $filename);
  #die "$filename = $deps" if $deps; # debug
  
  my @dep = $xml =~ m/<bdep name="([^"]+)"/g;
  my @subpack = $xml =~ m!<subpack>([^<>]+)</subpack>!g;
  #die "$pkg @subpack @dep" if $pkg eq "bash"; # debug
  #die "$pkg @subpack @dep" if @dep; # debug
  $pkgmapsrcbin{$pkg} = \@subpack;
  $pkgmapsrcdep{$pkg} = \@dep;
}

# dump parsed maps
my $coder = JSON::XS->new->pretty->canonical;
for my $map (qw(pkgmapsrcdep pkgmapsrcbin)) {
  dumpmap $map;
}

sub dumpmap($)
{ my $mapname=shift;
  mkdir("out");
  open(F, ">out/$mapname") or die;
  print F $coder->encode(eval '\%'.$mapname);
}
