#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

slowrollstats - Plugin to measure slowroll updates.

=head1 NOTES

FIXME

=head1 AUTHOR

Contributed by Bernhard M. Wiedemann

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. "$MUNIN_LIBDIR/plugins/plugin.sh"

if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

if [ "$1" = "config" ]; then

        echo 'graph_title Slowroll updates'
        echo 'graph_args --base 1000 -l 0 '
        echo 'graph_scale yes'
        echo 'graph_vlabel packages'
        echo 'graph_category system'
        echo 'pkgs.label packages'
        echo 'pkgs.draw AREA'
        echo 'pkgs.min 0'
        echo 'slowrollpkgs.label sr packages'
        echo 'slowrollpkgs.draw AREA'
        echo 'slowrollpkgs.min 0'
        print_warning pkgs
        print_critical pkgs
        exit 0
fi

dir=/srv/ftp/pub/opensuse/update/slowroll/repo/oss/src
echo pkgs.value `ls $dir | wc -l`
echo slowrollpkgs.value `ls $dir | grep '[0-9]\.sr20[2-9][0-9][0-9][0-9][0-9][0-9]\.src\.rpm' | wc -l`

