#!/usr/bin/perl -w
use strict;
# help in pulling in trees of packages to resolve something
# usage:
#  osc buildinfo $slobuild python-importlib-metadata standard x86_64 | tools/autogather | bash -x
#  or: tools/autogather2 python-importlib-metadata   (arch=i586 to override)

while (<>) {
  my @m = (m/nothing provides (\S+)/g);
  my %pkg = ();
  foreach my $m (@m) {
    $m=~s!</error>!!;
    $m=~s!,$!!;
    $m=~s/python3\d+/python/; # python39, python313, python315, ...
    $m=~s/python3/python/;
    $m=~s/(rubygem)\((\S+)\)/$1-$2/;
    $m=~s/pkgconfig\((\S+)\)/$1/;
    $m=~s/-devel$//;
    if($m=~/perl\(([^()]+)\)/) {
        my $n = $1; $n=~s/::/-/g;
        $m = "perl-$n";
    }
    $pkg{$m} = 1;
  }
  foreach my $k (sort keys %pkg) {
    print "tools/submitpackageupdate $k\n";
  }
}
