#!/usr/bin/perl -w
use strict;
use lib "lib";
use common;

$|=1;
our $repo = shift || die "usage: $0 openSUSE:Slowroll";
our $keeplist = load_list_map "in/never-update-exceptions";

my $packages = `osc ls $repo | grep -v :`;
my @packages = split("\n", $packages);

#print "@packages\n";
foreach my $p (@packages) {
    next if $keeplist->{$p} and not $ENV{FORCE};
    diag("osc rdelete --force -m cleanuprepo $repo $p");
    $ENV{prj}=$repo;
    $ENV{pkg}=$p;
    system('. tools/osc.sh; time osc_delete "/source/$prj/$pkg?force=1&comment=cleanuprepo"');
    #system(qw(osc rdelete --force -m cleanuprepo), $repo, $p);
}

