#!/usr/bin/perl -w
use strict;
use lib "lib";
use common;

our $repo = shift || die "usage: $0 openSUSE:Slowroll";
our $keeplist = load_list_map "in/never-update-exceptions";

my $packages = `osc ls $repo`;
my @packages = split("\n", $packages);

#print "@packages\n";
foreach my $p (@packages) {
    next if $keeplist->{$p};
    diag("osc rdelete -m cleanuprepo $repo $p");
    system(qw(osc rdelete -m cleanuprepo), $repo, $p);
}

