#!/usr/bin/perl -w
use strict;

my $pkglist = `osc ls openSUSE:Slowroll`;

my %pkg=();
my @cleanpkgs=qw(kernel-source kernel-source-longterm);

foreach(split("\n", $pkglist)) {
    next if /:/;
    foreach my $p (@cleanpkgs) {
      if(m/$p\./) { push(@{$pkg{$p}}, $_) }
    }
}

foreach my $p (@cleanpkgs) {
    my $n=0;
    for (1..6) {pop(@{$pkg{$p}})} # always keep last kernels
    foreach(@{$pkg{$p}}) {
        next if $n++ % 2;
        print "cleaning up $_\n";
	system(qw"osc rdelete -m cleanup-kernel openSUSE:Slowroll", $_) unless $ENV{DEBUG};
    }
}
