#!/usr/bin/perl -w
use strict;

our $prj = $ENV{slou} || 'openSUSE:Slowroll';
my $pkglist = `osc ls $prj`;

my %pkg=();
my @cleanpkgs=qw(kernel-source kernel-source-longterm);
#push(@cleanpkgs, (split("\n", `grep -v '#' in/kmps`)));

foreach(split("\n", $pkglist)) {
    next if /:/;
    foreach my $p (@cleanpkgs) {
      if(m/$p\./) { push(@{$pkg{$p}}, $_) }
    }
}

foreach my $p (@cleanpkgs) {
    my $n=0;
    for (1..9) {pop(@{$pkg{$p}})} # always keep last kernels
    foreach(@{$pkg{$p}}) {
        next if $n++ % 2;
        print "cleaning up $_\n";
	system(qw"osc rdelete -m cleanup-kernel", $prj, $_) unless $ENV{DEBUG};
    }
}
