#!/usr/bin/perl -w
# SPDX-License-Identifier: GPL-2.0-only
# suggest entries for in/coupled-rebuilds + in/coupled-updates from versioned
# cross-source requires in the TW *binary* repo metadata (see "make findcoupled")
# usage: tools/findcoupled.pl [primary.xml.zst] # suggestions on stdout, warnings on stderr

use strict;
use lib "lib";
use common;
use rpm;
$| = 1;

my $primary = shift // "cache/tumbleweed-bin/primary.xml.zst";

sub unxml($)
{ my $s = shift;
    $s =~ s/&lt;/</g;
    $s =~ s/&gt;/>/g;
    $s =~ s/&quot;/"/g;
    $s =~ s/&amp;|&#38;/&/g;
    return $s;
}

# sourcerpm is not always the OBS package name - see disturl2pkg in lib/rpm.pm
my %binobssrc;
if (-e "out/pkgmapsrcbin") {
    my $srcbin = load_json("out/pkgmapsrcbin");
    foreach my $src (sort keys %$srcbin) {
        (my $s = $src) =~ s/:.*//; # drop the multibuild flavor
        $binobssrc{$_} = $s foreach @{$srcbin->{$src}};
    }
} else {
    print STDERR "NOTE: out/pkgmapsrcbin missing (regenerated by make newsnapshot1)"
        ." - falling back to sourcerpm names, which are not always the OBS"
        ." package name. Check suggestions with: osc ls openSUSE:Factory NAME\n";
}

my %prov;   # provide name => [{bin, src, epoch, ver, rel}]
my %reqs;   # binary => [[name, flags, epoch, ver, rel]] - only versioned EQ/GE
my %binsrc; # binary => source package
my %binver; # binary => {epoch, ver}
my $entryre = qr{<rpm:entry name="([^"]+)"(?: flags="([A-Z]+)" epoch="([^"]*)" ver="([^"]*)"(?: rel="([^"]*)")?)?};

open(my $fh, '-|', decompressor($primary)." -cd $primary")
    or die "cannot read $primary : $!";
{ local $/ = "</package>\n"; # stream per package - the file is too big to slurp
while (my $chunk = <$fh>) {
    next unless $chunk =~ m{<arch>(?:x86_64|noarch)</arch>}; # i586 duplicates these
    my ($bin) = $chunk =~ m{<name>([^<]+)</name>} or next;
    next if exists $binsrc{$bin};
    my ($epoch, $ver, $rel) = $chunk =~ m{<version epoch="([^"]*)" ver="([^"]*)" rel="([^"]*)"};
    my ($srcrpm) = $chunk =~ m{<rpm:sourcerpm>([^<]*)</rpm:sourcerpm>};
    unless ($srcrpm) {
        print STDERR "WARN: no sourcerpm for $bin - skipped\n";
        next;
    }
    (my $src = $srcrpm) =~ s/-[^-]+-[^-]+\.(?:no)?src\.rpm$//;
    $src = $binobssrc{$bin} // $src;
    $binsrc{$bin} = $src;
    $binver{$bin} = { epoch => $epoch || "0", ver => $ver, rel => $rel };
    if ($chunk =~ m{<rpm:provides>(.*?)</rpm:provides>}s) {
        my $block = $1;
        while ($block =~ m{$entryre}g) {
            push(@{$prov{unxml($1)}}, { bin => $bin, src => $src });
        }
    }
    if ($chunk =~ m{<rpm:requires>(.*?)</rpm:requires>}s) {
        my $block = $1;
        while ($block =~ m{$entryre}g) {
            my ($name, $flags, $e, $v, $r) = (unxml($1), $2, $3, $4, $5);
            next unless defined $flags and $flags =~ /^(?:EQ|GE)$/ and defined $v;
            push(@{$reqs{$bin}}, [$name, $flags, $e || "0", $v, $r]);
        }
    }
}
}
close($fh);
die "parsed no packages from $primary" unless %binsrc;
(my $primarydir = $primary) =~ s{/[^/]*$}{};
prune_old_primaries($primarydir, $primary) if $primarydir ne $primary;
diag scalar(keys %binsrc)." binary packages, ".scalar(keys %prov)." provides";

my $kmps = load_list_map("in/kmps");
my %suggest; # file => trigger => dep => evidence
my ($unresolved, $broken) = (0, 0);

sub couple($$$$)
{ my ($file, $trigger, $dep, $evidence) = @_;
    return if $suggest{$file}{$dep}{$trigger}; # one direction is enough
    $suggest{$file}{$trigger}{$dep} //= $evidence;
}

foreach my $bin (sort keys %reqs) {
    my $reqsrc = $binsrc{$bin};
    foreach my $r (@{$reqs{$bin}}) {
        my ($name, $flags, $e, $v, $rl) = @$r;
        next if $name =~ /^config\(/ or $name =~ /-debug(?:info|source)$/;
        my @cross = grep { $_->{src} ne $reqsrc } @{$prov{$name} // []};
        next unless @cross;
        # kernel couplings are handled by tools/kernelupdate*
        next if $reqsrc =~ /^kernel/ or $kmps->{$reqsrc};
        my %bysrc;
        $bysrc{$_->{src}} //= $_ foreach @cross;
        if (keys %bysrc > 1) {
            our %warned;
            print STDERR "WARN: skipping $name (required by $bin): provided by"
                ." multiple sources: ".join(" ", sort keys %bysrc)."\n"
                unless $warned{$name}++;
            next;
        }
        my ($p) = values %bysrc;
        next if $p->{src} =~ /^kernel/;
        # compare against the provider's *package* version - matching only a
        # versioned provide (e.g. typelib(Atk) = 1.0) is no version coupling
        my $pv = $binver{$p->{bin}};
        my $matchprov = $v eq $pv->{ver} && $e eq $pv->{epoch}
            && (!defined $rl || $rl eq $pv->{rel});
        my $matchreq = $v eq $binver{$bin}{ver} && $e eq $binver{$bin}{epoch};
        my $constraint = "$name ".($flags eq "EQ" ? "=" : ">=")." $v";
        if ($flags eq "EQ") {
            if ($matchprov and $matchreq) {
                couple("in/coupled-rebuilds", $p->{src}, $reqsrc,
                    "$bin requires $constraint (direction ambiguous - versions coincide)");
            } elsif ($matchprov) { # requirer baked the provider's version in
                couple("in/coupled-rebuilds", $p->{src}, $reqsrc, "$bin requires $constraint");
            } elsif ($matchreq) { # provider tracks the requirer's version, e.g. NM-branding
                couple("in/coupled-rebuilds", $reqsrc, $p->{src},
                    "$bin requires $constraint (tracks $reqsrc version)");
            } else { # API-versioned EQ like typelib(Atk) = 1.0, or stale
                $broken++;
                diag "no version coupling: $bin requires $constraint, $p->{bin} has $pv->{ver}";
            }
        } elsif ($matchprov and $bin !~ /-devel$/) { # >= current version hints at lockstep updates
            couple("in/coupled-updates", $reqsrc, $p->{src},
                "$bin requires $constraint, the current version of $p->{src}");
        }
    }
}
$unresolved = grep { !$prov{$_->[0]} } map { @$_ } values %reqs;
print STDERR "$unresolved versioned requires without provider, "
    ."$broken EQ not matching any package version (details with DEBUG=1)\n";

my %existing; # unordered "a b" pair => the in/ file listing it
foreach my $file ("in/coupled-updates", "in/coupled-rebuilds") {
    foreach my $group (@{load_list_of_lists($file)}) {
        my ($trigger, @rest) = @$group;
        $existing{join(" ", sort($trigger, $_))} = "$file: $trigger $_" foreach @rest;
    }
}

my (%confirmed, %new);
foreach my $file (sort keys %suggest) {
    foreach my $trigger (sort keys %{$suggest{$file}}) {
        foreach my $dep (sort keys %{$suggest{$file}{$trigger}}) {
            my $evidence = $suggest{$file}{$trigger}{$dep};
            if (my $entry = $existing{join(" ", sort($trigger, $dep))}) {
                $confirmed{$entry} //= $evidence;
            } else {
                $new{$file}{$trigger}{$dep} = $evidence;
            }
        }
    }
}

foreach my $file (sort keys %new) {
    my $note = $file =~ /updates/ ? " (heuristic candidates - verify each before adding)" : "";
    print "# --- suggested additions to $file$note ---\n";
    foreach my $trigger (sort keys %{$new{$file}}) {
        my @deps = sort keys %{$new{$file}{$trigger}};
        print "$trigger @deps # ".join("; ", map { $new{$file}{$trigger}{$_} } @deps)."\n";
    }
    print "\n";
}
print "# --- existing entries confirmed by repo evidence ---\n";
print "# $_ # $confirmed{$_}\n" foreach sort keys %confirmed;
print "# --- existing entries without repo evidence (can be fine - not all coupling is visible in metadata) ---\n";
foreach my $pair (sort keys %existing) {
    print "# $existing{$pair}\n" unless $confirmed{$existing{$pair}};
}
