#!/usr/bin/perl -w
# Derive the next generation's slorc by flipping generation digits.
# usage: tools/nextslorc <~/.slorc >~/.slorc.next
#
# This replaces a blind `tr 12 21`, which rewrote every 1 and 2 in the file -
# years in comments, the port in stage3.opensuse.org:17080, a RELEASE_SETTLE of
# 1m, a SILENT=1 - and so quietly imposed the rule that nothing else in the file
# may contain those digits.
#
# A generation digit is either the whole value of slon=, or a whole
# colon/slash-delimited component, which is what openSUSE:Slowroll:Base:1 and
# .../Slowroll:/1/standard/ are and what :17080 or 2026-01-02 are not.

use strict;

while(<>) {
    s/^(\s*(?:export\s+)?slon=)([12])(?![0-9])/$1.(3-$2)/e;
    s{(?<=[:/])([12])(?=[:/\s]|$)}{3-$1}ge;
    print;
}
