#!/usr/bin/perl -w
# sync sources and binaries in a project
# e.g. openSUSE:Slowroll:Base:2 and openSUSE:Factory
# support partial sync via filter function
# like rsync, this should be efficient in handling deltions, additions and updates
# overlaps with tools/syncslob
# tools/obsrsync $(cat in/missing-dvd-rpms)
use strict;
use XML::Bare;
use lib 'lib';
use common;


my $src = "openSUSE:Factory";
my $dest = $ENV{slobase};
my @pkgs = @ARGV;
if (!@pkgs) {
    die "usage: $0 PGK1 PKG2 ..."
}
my $dry = ($ENV{DRYRUN}//1)==0 ? "":"echo";
my $srcbin = load_json("out/pkgmapsrcbin");
my %binsrc;
my %allbins;
while(my @a = each(%$srcbin)) {
    my $p = $a[0]; $p=~s/:.*//;
    push(@{$allbins{$p}}, @{$a[1]});
    foreach my $bin (@{$a[1]}) {
        $binsrc{$bin} = $a[0];
    }
} 
#my $src32ref  = new XML::Bare(text => cache_or_run("cache/factory-i586.xml", sub{ `osc api /build/$src/standard/i586/_repository?view=binaryversions` })) ->parse();
my $srcref  = new XML::Bare(text => cache_or_run("cache/factory-x86_64.xml", sub{ `osc api /build/$src/standard/x86_64/_repository?view=binaryversions` })) ->parse();
#my $dest32ref = new XML::Bare(text => cache_or_run("cache/slob-i586.xml",   sub{ `osc api /build/$dest/standard/i586/_repository?view=binaryversions` })) ->parse();
my $destref = new XML::Bare(text => cache_or_run("cache/slob-x86_64.xml",   sub{ `osc api /build/$dest/standard/x86_64/_repository?view=binaryversions` })) ->parse();

sub process_binaryversions($)
{ my ($ref) = @_;
    my %ret=();
    foreach my $bin (@{$ref->{binaryversionlist}->{binary}}) {
        my $name = $bin->{name}->{value}; $name =~ s/\.rpm$//;
	$ret{$name} = $bin->{hdrmd5}->{value};
    }
    $_[0] = \%ret; # replace input - slightly unclean but easier to use
    return \%ret;
}

process_binaryversions($srcref);
process_binaryversions($destref);

for my $pkg (@pkgs) {
    my $allsynced = 1;
    foreach my $bin (@{$allbins{$pkg}}) {
	my $srcver=$srcref->{$bin};
        next unless $srcver;
        my $destver=$destref->{$bin}//"missing";
        #diag("comparing $pkg $bin $srcver $destver");
        if($destver ne $srcver) {$allsynced=0}
    }
    next if $allsynced;
    system "$dry osc release $src --target-project=$dest '$pkg' --target-repository=standard -r standard"
}
