#!/bin/bash
if [[ $DEBUG ]] ; then set -x ; fi
slo=openSUSE:Slowroll
# from https://github.com/bmwiedemann/build-compare/tree/slowroll
dry=echo
[ "$DRYRUN" = 0 ] && dry=

FORCE=1 $dry tools/cleanuprepo $sloreleasing
#pkgs=`osc ls $slo:Staging`
shopt -s nullglob
pkgs=out/pending/*
releasedpkgs=""
for pkg in $pkgs ; do
    tools/releasestagingone "$pkg" && releasedpkgs="$releasedpkgs $pkg"
done
[ -n "$releasedpkgs" ] || exit 0 # done
sleep 20m # TODO wait for completion of deferred release jobs
( cd /
$dry osc release --no-delay $sloreleasing
)
# Instead of waiting here for completion, we delay the cleanup to next start
if [ -z "$dry" -a -n "$releasedpkgs" ] ; then
    tag=`tools/findlastrelease`
    # link released packages to standard name
    for pkg in $releasedpkgs ; do
        pkg=$(basename "$pkg")
        osc linkpac -f "$slo" "$pkg.$tag" "$slo" "$pkg"
    done
fi
