#!/bin/bash
if [[ $DEBUG ]] ; then set -x ; fi
slo=openSUSE:Slowroll
# from https://github.com/bmwiedemann/build-compare/tree/slowroll
bc=build-compare
: ${RELEASE_UNREPRODUCIBLE:=true}
dry=echo
[ "$DRYRUN" = 0 ] && dry=
: ${offline:=false}
mkdir -p tmp

function osc_getbinaries
{
    repo=$1
    pkg=$2
    dest=$3
    osc ls -b $repo $pkg standard x86_64 | grep -q .
    ret=$?
    if [[ $ret = 0 ]] ; then
        osc getbinaries --sources --destdir=$dest $repo $pkg standard x86_64
        rm -f $dest/rpmlint.log
        rm -f $dest/::import::i586::*-32bit*.rpm # workaround missing i586 builds in Slowroll - if 64-bit binaries match, we just use the TW version
    fi
    return $ret
}


pkg="$1"
  pkg=$(basename "$pkg")
  if ! $RELEASE_UNREPRODUCIBLE && grep ^$pkg in/build-compare-differed-builds.txt ; then
    echo "skipping unreproducible package $pkg..."
    exit 0
  fi
  # fetch binaries from Factory + Staging
  if ! $offline ; then
    rm -rf tmp/{slo,slos,slos.s,fac}
    osc r -r standard -a x86_64 $slobuild $pkg | grep -q ' succeeded' || exit 0

    osc_getbinaries $slobuild        $pkg tmp/slos
    osc_getbinaries $slo             $pkg tmp/slo ||
    osc_getbinaries $slobase         $pkg tmp/slo
    mkdir tmp/slos.s
    mv tmp/slos/*.src.rpm tmp/slos.s
  fi

  # build-compare with special exception for disturl+distribution
  if $bc/same-build-result.sh tmp/slo tmp/slos tmp/slos.s ; then
    # skip release if same
    $dry rm out/pending/$pkg
    exit 0
  fi
  $offline || osc_getbinaries openSUSE:Factory $pkg tmp/fac
  equivalent=false
  if $bc/same-build-result.sh tmp/fac tmp/slos tmp/slos.s ; then
    equivalent=true
  fi
  src=$slobuild
  if $equivalent || grep -q "^$pkg$" in/kernel-update-exceptions ; then
    src=openSUSE:Factory
  fi
  echo "XX releasing $src $pkg"
  $dry tools/releasemulti "$src" "$slo:Releasing" "$pkg"
  #$dry osc rdelete -m "released" $slobuild $pkg &&
  $dry rm out/pending/$pkg
