#!/usr/bin/perl -w
# one source package such as kernel-source can contain multiple .spec files
# and we need to call osc release for all of them individually

use strict;
use lib 'lib';
use common;

$|=1;
our $srcprj = shift;
our $dstprj = shift;
my $pkg = shift;
our $dryrun = $ENV{DRYRUN}//0;

if(!$pkg) {
    die "usage: $0 SRCPRJ DSTPRJ PKG\n";
}

sub release_one($)
{ my($pkg) = @_;
    diag("release $srcprj $pkg $dstprj");
    system('osc', 'release', '--no-delay', $srcprj, '--target-project', $dstprj, $pkg, '--target-repository=standard', '-r', 'standard') unless $dryrun;
    if($dstprj eq $ENV{slo}) { # this is a maintenance project and we need to update links
        my $tag=`tools/findlastrelease`; chomp($tag);
        # link released packages to standard name
        system(qw(osc linkpac -f), $dstprj, "$pkg.$tag", $dstprj, $pkg);
    }
}

my $ls = `osc ls -e $srcprj $pkg | grep \\\\.spec\$`;
diag($ls);
release_one($pkg);
