#!/usr/bin/perl -w
# one source package such as kernel-source can contain multiple .spec files
# and we need to call osc release for all of them individually

use strict;
use lib 'lib';
use common;

$|=1;
our $srcprj = shift;
our $dstprj = shift;
my $pkg = shift;
our $dryrun = $ENV{DRYRUN}//0;

if(!$pkg) {
    die "usage: $0 SRCPRJ DSTPRJ PKG\n";
}

sub release_one($)
{ my($pkg) = @_;
    diag("release $srcprj $pkg $dstprj");
    foreach($srcprj, $dstprj, $pkg) { die 'invalid char in sanity check' if m/[^a-zA-Z0-9:._+-]/ }
    system(qq!. tools/osc.sh ; osc_post '/source/$srcprj/$pkg?cmd=release&repository=standard&target_project=$dstprj&target_repository=standard&nodelay=1' ''!) unless $dryrun;
    #system('osc', 'release', '--no-delay', $srcprj, '--target-project', $dstprj, $pkg, '--target-repository=standard', '-r', 'standard') unless $dryrun;
    if($dstprj eq $ENV{slo}) { # this is a maintenance project and we need to update links
        my $tag=`tools/findlastrelease`; chomp($tag);
        # link released packages to standard name
        system(qw(osc linkpac -f), $dstprj, "$pkg.$tag", $dstprj, $pkg);
    }
}

if(0) { # detect files in symlink that would cause trouble
    my $ls = `osc ls -e $srcprj $pkg | grep \\\\.spec\$`;
    diag($ls);
}
release_one($pkg);
