#!/bin/sh
#curl -s https://api.opensuse.org/public/source/openSUSE:Slowroll:Base:Next/000product/openSUSE.product|grep '<version>2'|grep -o '[0-9]*'
curl -s https://api.opensuse.org/public/source/${slobuild}/000release-packages/openSUSE-release.spec?expand=1|grep '^Version:'|grep -o '[0-9]*'
