#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-only
pkg=$1
if [ -z "$pkg" ] ; then
    echo "Usage: $0 PKG"
    echo "submits a package named PKG from Tumbleweed to Slowroll"
    exit 1
fi

osc copypac -e -K openSUSE:Factory "$pkg" openSUSE:ALP:Experimental:Slowroll
