#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-only
pkg=$1
rev=${2:-latest}
srcprj=openSUSE:Factory
dstprj=$slobuild

if [ -z "$pkg" ] ; then
    echo "Usage: $0 PKG"
    echo "submits a package named PKG from Tumbleweed to Slowroll"
    exit 1
fi

if [ $rev = latest ] ; then
    rev=$(osc log $srcprj "$pkg" |
        head -2 |tail -1 |
	grep -E -o ' [a-f0-9]{32} ' | sed 's/ //g')
fi

# find out if it has any diff:
if [[ $FORCE ]] || [[ -n `PAGER="wc -c" osc rdiff --missingok -r $rev $srcprj "$pkg" $dstprj` ]] ; then
    export rev
    vrev=`tools/findcireleasecounter $srcprj $pkg`
    echo "submitting $pkg $vrev ..."
    osc branch -f -r $rev --nodevelproject $srcprj "$pkg" $dstprj
    if [[ -n "$vrev" ]] ; then
        osc setlinkrev --vrev "$vrev.0" -r $rev $dstprj "$pkg"
    fi
    #osc detachbranch -m "drop link" $dstprj "$pkg"
    touch out/pending/$pkg
else
    echo "no diff"
fi
