#!/bin/sh
# flip the Base:1 / Base:2 references in a project's meta to the other generation
# usage: tools/switchbase [PRJ]   # default $slo:Base
: ${slo:=openSUSE:Slowroll}
export slo
prj=${1:-$slo:Base}
osc meta prj $prj |
    perl -pe 'BEGIN{$b=quotemeta("$ENV{slo}:Base:")} s/($b)([12])/$1.(3-$2)/ge' > .tmp
osc meta prj -F .tmp $prj
rm .tmp
