#!/usr/bin/perl -w
use strict;
#input from stage3:
#for p in slowroll/repo/src-oss/src/* ; do rpm -qp --qf '%{name} %{version} %{release} %{disturl}\n' $p ; done > .slowroll
# and from tools/getrepoviews
use lib 'lib';
use common;
$|=1;

open(F1, "<cache/slowroll-base.disturls") or die $!; # created on stage3 with /srv/ftp/pub/opensuse # for p in slowroll/repo/src-oss/src/* ; do rpm -qp --qf '%{name} %{version} %{release} %{disturl}\n' $p ; done > .slowroll
# or pontifex (download.o.o):/srv/ftp/pub/opensuse/repositories/openSUSE:/ALP:/Experimental:/Slowroll/base.20240212/repo/src-oss/src # for p in * ; do rpm -qp --qf '%{name} %{version} %{release} %{disturl}\n' $p ; done > .slowroll
#curl downloadcontent.opensuse.org/repositories/openSUSE:/ALP:/Experimental:/Slowroll/base.20240212/repo/src-oss/src/.slowroll > cache/slowroll-base-20240212.disturls
my $slob = load_json("cache/view.2024-02-15/slob.json");

while(<F1>) {
    my ($name, $version, $release, $disturl) = split();
    my $md5 = $disturl;
    $md5 =~ s,^obs://build.opensuse.org/openSUSE:Factory/standard/,,;
    $md5 =~ s,-$name$,, or next;
    my $slobmd5 = $slob->{$name}{md5}//"newpkg";
    next if $slobmd5 eq $md5;
    print STDERR "$name\t$md5\n";
    print "osc copypac -r $md5 openSUSE:Factory $name openSUSE:Slowroll:Base\n";
}
