#!/bin/sh
osc api -X POST "/source/$slobuild?cmd=remove_flag&flag=build"
osc api -X POST "/source/$slobuild?cmd=remove_flag&flag=publish"

#echo later: osc api -X POST "/source/$slo?cmd=remove_flag&flag=publish" # moved to post2
