#!/bin/sh
#usage:
#for p in $(osc ls $slo:Staging | grep -v :) ; do echo "$p"; tools/syncslos-postbump "$p" ; done | tee out/log/syncslos-postbump-$(date -I)
srcprj=openSUSE:Factory
prj=openSUSE:Slowroll:Staging
pkg=${1:-qt6-webview}
basedisturls=cache/slowroll-base.disturls

grep "^$pkg$" in/never-update-exceptions && exit 0

#osc api "/source/$prj/$pkg/_history"|tail -3|grep -q adrianSuSE
isold=0
#$?

if [ $isold != 0 ] ; then
  echo "keeping new $pkg"
  exit 0 # for now keep new pkgs
fi

if \
   grep -q "^$pkg$" in/baselibs.list in/dont-delete ||
   osc ls -b -a i586 $prj "$pkg" | grep -q . ||
   osc ls -b -a x86_64 $prj "$pkg" | grep -q -- -bootstrap ; then
  echo "updating $pkg"
  rev=$(basename $(grep ^$pkg\  $basedisturls|cut -d" " -f4) |cut -d- -f1)
  if PAGER="wc -c" osc rdiff --missingok -r "$rev" $srcprj "$pkg" $prj | grep -q . ; then
  osc copypac -r "$rev" $srcprj "$pkg" $prj
  fi
else
  echo "dropping $pkg"
  osc rdelete --force -m "rebased" $prj "$pkg"
  rm -f "out/pending/$pkg"
fi
