#!/bin/sh
#usage:
#for p in $(osc ls $slo) ; do echo "$p"; tools/syncslo-postbump "$p" ; done | tee out/log/syncslo-postbump-$(date -I)
srcprj=openSUSE:Factory
prj=openSUSE:Slowroll
pkg=${1:-qt6-webview}
basedisturls=cache/slowroll-base.disturls
factoryjson=cache/view.2024-02-15/factory.json
dry=echo
dry=

grep "^$pkg$" in/never-update-exceptions && exit 0

if ! grep -q "^$pkg$" in/baselibs.list in/i586bitbuilddeps in/dont-delete ; then
##osc api "/source/$prj/$pkg/_history"|tail -3|grep -q "Release from openSUSE:Factory" # does not work because of :Releasing subprj
#osc api /build/$srcprj/standard/x86_64/$pkg/_buildenv > tmp/srcenv
#osc api /build/$prj/standard/x86_64/$pkg/_buildenv > tmp/dstenv
#diff tmp/{src,dst}env >/dev/null
#isfactory=$?


#if [ $isfactory = 0 ] ; then
    echo "dropping $pkg"
    $dry osc rdelete -m "rebased" $prj "$pkg"
    exit 0 # done
#fi
fi

echo "updating $pkg"
rev=$(basename $(grep ^$pkg\  $basedisturls|cut -d" " -f4) |cut -d- -f1)
frev=$(jq ".[\"$pkg\"][\"md5\"]" $factoryjson | sed 's/"//g')
if [[ $rev = $frev ]] ; then
#if PAGER="wc -c" osc rdiff --missingok -r "$rev" $srcprj "$pkg" $prj | grep -q . ; then # check if there is any diff
#echo osc copypac -r "$rev" $srcprj "$pkg" $prj
    $dry tools/releasemulti $srcprj $prj "$pkg"
else
    echo "XX mismatch in $pkg $rev vs $frev"
fi
