#!/bin/sh
#usage:
#for p in $(osc ls $slo|grep -v :|sort -r) ; do echo "$p"; dry=" " tools/syncslo-postbump "$p" ; done | tee out/log/syncslo-postbump-$(date -I)
srcprj=openSUSE:Factory
prj=openSUSE:Slowroll
pkg=${1:-qt6-webview}
# from pontifex2 cd /srv/ftp/pub/opensuse/repositories/openSUSE:/ALP:/Experimental:/Slowroll/base.20240405/repo/src-oss/src && for p in * ; do rpm -qp --qf '%{name} %{version} %{release} %{disturl}\n' $p ; done > .slowroll
# from curl https://downloadcontent.opensuse.org/repositories/openSUSE:/ALP:/Experimental:/Slowroll/base-next-full/repo/src-oss/src/.slowroll > cache/slowroll-base.disturls
basedisturls=cache/slowroll-base.disturls
# needs to be the info on current binaries to not get too new versions
factoryjson=cache/view/factory.json
: ${dry:=echo}

. tools/osc.sh

xpkg=$(echo "$pkg" | perl -pe 's/\.202[45]\d{10}//') # handle maintenance release naming FIXME update in 2026

if [ "$xpkg" = "$pkg" ] ; then
    osc_api "source/$prj/$pkg" 2>&1 | grep -q '<linkinfo .*error=.*does not exist' &&
        echo "drop dangling link $prj/$pkg" &&
        $dry osc_delete "source/$prj/$pkg?force=1&comment=drop-dangling-link"
        #$dry osc rdelete --force -m "drop-dangling-link" $prj "$pkg"
    exit 0
fi

grep "^$xpkg$" in/never-update-exceptions && exit 0

pkgmonth=$(echo "$pkg" | perl -pe 's/.*\.(\d{6})\d{8}$/$1/')
currentmonth=$(date -u +%Y%m)
if ! grep -q "^$xpkg$" in/dont-delete in/i586bitbuilddeps1 in/kmps && test "$pkgmonth" != "$currentmonth" ; then
#if ! grep -q "^$pkg$" in/baselibs.list in/i586bitbuilddeps in/dont-delete ; then
##osc api "/source/$prj/$pkg/_history"|tail -3|grep -q "Release from openSUSE:Factory" # does not work because of :Releasing subprj
#osc api /build/$srcprj/standard/x86_64/$pkg/_buildenv > tmp/srcenv
#osc api /build/$prj/standard/x86_64/$pkg/_buildenv > tmp/dstenv
#diff tmp/{src,dst}env >/dev/null
#isfactory=$?


#if [ $isfactory = 0 ] ; then
    echo "dropping $pkg"
    $dry osc_delete "source/$prj/$pkg?force=1&comment=rebased"
    #$dry osc rdelete --force -m "rebased" $prj "$pkg"
    exit 0 # done
#fi
fi

latest=$(tools/followlink $xpkg)
if [ "$pkg" != "$latest" ] ; then
    #grep -q "^$xpkg$" in/dont-delete in/kmps && exit 0
    grep -q "^$xpkg$" in/dont-delete2 in/kmps && exit 0
    echo "drop old version" "$prj" "$pkg"
    $dry osc_delete "source/$prj/$pkg?force=1&comment=drop-old-version"
    #$dry osc rdelete --force -m "drop-old-version" "$prj" "$pkg"
    exit 0
fi

echo "updating $pkg"
rev=$(basename $(grep ^$xpkg\  $basedisturls|cut -d" " -f4) |cut -d- -f1)
frev=$(jq ".[\"$xpkg\"][\"md5\"]" $factoryjson | sed 's/"//g')
if [[ $rev = $frev ]] ; then
#if PAGER="wc -c" osc rdiff --missingok -r "$rev" $srcprj "$pkg" $prj | grep -q . ; then # check if there is any diff
#echo osc copypac -r "$rev" $srcprj "$pkg" $prj
    grep -q "^$xpkg$" in/i586bitbuilddeps1 && exit 0
    $dry tools/releasemulti $srcprj $prj "$xpkg"
    grep -q "^$xpkg$" in/dont-delete in/kmps && exit 0
    $dry osc_delete "source/$prj/$pkg?force=1&comment=updated-from-Factory"
    #$dry osc rdelete --force -m "updated-from-Factory" "$prj" "$pkg"
else
    echo "XX mismatch in $pkg $rev vs $frev => submitting as update"
    $dry tools/submitpackageupdate "$xpkg" "$rev"
fi
