#!/bin/sh
ver=$(tools/slowrollverobsnext)
echo "preparing to take snapshot of version $ver... can take some hours until pontifex picks it up"
echo "$ver" | ssh slowroll@vm12cg.zq1.de. dd of=/srv/www/slowroll/nextsnapshot
if [[ $? != 0 ]] ; then
    echo "failed - please check + retry"
    exit 12
fi
while sleep 60 ; do
    nextver=$(tools/slowrollvernext)
    if [[ $nextver = $ver ]] ; then
        break
    fi
done
