#!/bin/sh -x
# these scripts are tracked in https://github.com/openSUSE/slowroll-tools/
# but are deployed on pontifex to create snapshots of Tumbleweed in an efficient manner
# usage: dry=" " slowroll-snapshot-2
b=/srv/ftp/pub/opensuse
: ${dry:=echo}
nversion=$(cat $b/repositories/openSUSE\:/ALP\:/Experimental\:/Slowroll/base-next/media.1/products | cut -d" " -f3|cut -c1-8 )
d1=$b/repositories/openSUSE\:/ALP\:/Experimental\:/Slowroll/base."$nversion"

# wait for publish of update repo:
refdate=$(date -d "4 hours ago" +%s)
while [[ $(cat /srv/ftp/pub/opensuse/update/slowroll/repo/oss/repodata/repomd.xml|grep -m1 timestamp | grep -E -o "[0-9]+") -lt $refdate ]] ; do
    sleep 5
done

$dry rm -rf /srv/ftp/pub/opensuse/debug/slowroll &&
  $dry ln -s slowroll.$nversion /srv/ftp/pub/opensuse/debug/slowroll

$dry rsync -aSHpv --delay-updates --link-dest=/srv/ftp/pub/opensuse/tumbleweed/ $d1/* $b/slowroll/

# cleanup previous version later to save storage space, but leave users time to sync
cd /srv/ftp/pub/opensuse/debug && find . -maxdepth 4 -name oss -path "./slowroll.20*/*" -mtime +90 | xargs -r rm -r
cd $d1/.. && find . -maxdepth 1 -name "base.20*" -mtime +340 | xargs -r rm -r

sleep 36h &&
  $dry rsync -a --delete-delay --delay-updates "$d1/" $b/slowroll/
