#!/bin/sh -x
# these scripts are tracked in https://github.com/openSUSE/slowroll-tools/
# but are deployed on pontifex to create snapshots of Tumbleweed in an efficient manner
# usage: dry=" " slowroll-snapshot-2
b=/srv/ftp/pub/opensuse
: ${dry:=echo}
nversion=$(cut -c 12-19 $b/repositories/openSUSE\:/ALP\:/Experimental\:/Slowroll/base-next/media.1/products)
d1=$b/repositories/openSUSE\:/ALP\:/Experimental\:/Slowroll/base."$nversion"

$dry rm -rf /srv/ftp/pub/opensuse/debug/slowroll &&
  $dry ln -s slowroll.$nversion /srv/ftp/pub/opensuse/debug/slowroll

$dry cp -afl $d1/* $b/slowroll/

# cleanup previous version later to save storage space, but leave users time to sync
cd /srv/ftp/pub/opensuse/debug && find . -maxdepth 4 -name oss -path "./slowroll.20*/*" -mtime +90 | xargs -r rm -r
cd $d1/.. && find . -maxdepth 1 -name "base.20*" -mtime +140 | xargs -r rm -r

sleep 36h &&
  $dry rsync -a --delete-delay --delay-updates "$d1/" $b/slowroll/
